# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stonks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stonks.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z,github.com/team-stonks/stonks-api;stonks_api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cstonks.proto\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\x0fTelegramRequest\x12\x0f\n\x07Message\x18\x01 \x01(\t\"#\n\x13\x43ompanyStatsRequest\x12\x0c\n\x04\x46igi\x18\x01 \x01(\t\"\xc9\x04\n\x14\x43ompanyStatsResponse\x12\x15\n\rEbitdaMargins\x18\x01 \x01(\x01\x12\x15\n\rProfitMargins\x18\x02 \x01(\x01\x12\x14\n\x0cGrossMargins\x18\x03 \x01(\x01\x12\x19\n\x11OperatingCashflow\x18\x04 \x01(\x01\x12\x15\n\rRevenueGrowth\x18\x05 \x01(\x01\x12\x18\n\x10OperatingMargins\x18\x06 \x01(\x01\x12\x0e\n\x06\x45\x62itda\x18\x07 \x01(\x01\x12\x16\n\x0eTargetLowPrice\x18\x08 \x01(\x01\x12\x14\n\x0cGrossProfits\x18\t \x01(\x01\x12\x14\n\x0c\x46reeCashflow\x18\n \x01(\x01\x12\x19\n\x11TargetMedianPrice\x18\x0b \x01(\x01\x12\x14\n\x0c\x43urrentPrice\x18\x0c \x01(\x01\x12\x16\n\x0e\x45\x61rningsGrowth\x18\r \x01(\x01\x12\x14\n\x0c\x43urrentRatio\x18\x0e \x01(\x01\x12\x16\n\x0eReturnOnAssets\x18\x0f \x01(\x01\x12\x1f\n\x17NumberOfAnalystOpinions\x18\x10 \x01(\x01\x12\x17\n\x0fTargetMeanPrice\x18\x11 \x01(\x01\x12\x14\n\x0c\x44\x65\x62tToEquity\x18\x12 \x01(\x01\x12\x16\n\x0eReturnOnEquity\x18\x13 \x01(\x01\x12\x17\n\x0fTargetHighPrice\x18\x14 \x01(\x01\x12\x11\n\tTotalCash\x18\x15 \x01(\x01\x12\x11\n\tTotalDebt\x18\x16 \x01(\x01\x12\x14\n\x0cTotalRevenue\x18\x17 \x01(\x01\x12\x19\n\x11TotalCashPerShare\x18\x18 \x01(\x01\x32\x91\x01\n\tStonksApi\x12\x42\n\x14TelegramNotification\x12\x10.TelegramRequest\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x0fGetCompanyStats\x12\x14.CompanyStatsRequest\x1a\x15.CompanyStatsResponse\"\x00\x42.Z,github.com/team-stonks/stonks-api;stonks_apib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_TELEGRAMREQUEST = _descriptor.Descriptor(
  name='TelegramRequest',
  full_name='TelegramRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='TelegramRequest.Message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=79,
)


_COMPANYSTATSREQUEST = _descriptor.Descriptor(
  name='CompanyStatsRequest',
  full_name='CompanyStatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Figi', full_name='CompanyStatsRequest.Figi', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=116,
)


_COMPANYSTATSRESPONSE = _descriptor.Descriptor(
  name='CompanyStatsResponse',
  full_name='CompanyStatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='EbitdaMargins', full_name='CompanyStatsResponse.EbitdaMargins', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ProfitMargins', full_name='CompanyStatsResponse.ProfitMargins', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='GrossMargins', full_name='CompanyStatsResponse.GrossMargins', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OperatingCashflow', full_name='CompanyStatsResponse.OperatingCashflow', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RevenueGrowth', full_name='CompanyStatsResponse.RevenueGrowth', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OperatingMargins', full_name='CompanyStatsResponse.OperatingMargins', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ebitda', full_name='CompanyStatsResponse.Ebitda', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TargetLowPrice', full_name='CompanyStatsResponse.TargetLowPrice', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='GrossProfits', full_name='CompanyStatsResponse.GrossProfits', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FreeCashflow', full_name='CompanyStatsResponse.FreeCashflow', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TargetMedianPrice', full_name='CompanyStatsResponse.TargetMedianPrice', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CurrentPrice', full_name='CompanyStatsResponse.CurrentPrice', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EarningsGrowth', full_name='CompanyStatsResponse.EarningsGrowth', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CurrentRatio', full_name='CompanyStatsResponse.CurrentRatio', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReturnOnAssets', full_name='CompanyStatsResponse.ReturnOnAssets', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NumberOfAnalystOpinions', full_name='CompanyStatsResponse.NumberOfAnalystOpinions', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TargetMeanPrice', full_name='CompanyStatsResponse.TargetMeanPrice', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DebtToEquity', full_name='CompanyStatsResponse.DebtToEquity', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReturnOnEquity', full_name='CompanyStatsResponse.ReturnOnEquity', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TargetHighPrice', full_name='CompanyStatsResponse.TargetHighPrice', index=19,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalCash', full_name='CompanyStatsResponse.TotalCash', index=20,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalDebt', full_name='CompanyStatsResponse.TotalDebt', index=21,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalRevenue', full_name='CompanyStatsResponse.TotalRevenue', index=22,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalCashPerShare', full_name='CompanyStatsResponse.TotalCashPerShare', index=23,
      number=24, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=704,
)

DESCRIPTOR.message_types_by_name['TelegramRequest'] = _TELEGRAMREQUEST
DESCRIPTOR.message_types_by_name['CompanyStatsRequest'] = _COMPANYSTATSREQUEST
DESCRIPTOR.message_types_by_name['CompanyStatsResponse'] = _COMPANYSTATSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TelegramRequest = _reflection.GeneratedProtocolMessageType('TelegramRequest', (_message.Message,), {
  'DESCRIPTOR' : _TELEGRAMREQUEST,
  '__module__' : 'stonks_pb2'
  # @@protoc_insertion_point(class_scope:TelegramRequest)
  })
_sym_db.RegisterMessage(TelegramRequest)

CompanyStatsRequest = _reflection.GeneratedProtocolMessageType('CompanyStatsRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPANYSTATSREQUEST,
  '__module__' : 'stonks_pb2'
  # @@protoc_insertion_point(class_scope:CompanyStatsRequest)
  })
_sym_db.RegisterMessage(CompanyStatsRequest)

CompanyStatsResponse = _reflection.GeneratedProtocolMessageType('CompanyStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPANYSTATSRESPONSE,
  '__module__' : 'stonks_pb2'
  # @@protoc_insertion_point(class_scope:CompanyStatsResponse)
  })
_sym_db.RegisterMessage(CompanyStatsResponse)


DESCRIPTOR._options = None

_STONKSAPI = _descriptor.ServiceDescriptor(
  name='StonksApi',
  full_name='StonksApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=707,
  serialized_end=852,
  methods=[
  _descriptor.MethodDescriptor(
    name='TelegramNotification',
    full_name='StonksApi.TelegramNotification',
    index=0,
    containing_service=None,
    input_type=_TELEGRAMREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCompanyStats',
    full_name='StonksApi.GetCompanyStats',
    index=1,
    containing_service=None,
    input_type=_COMPANYSTATSREQUEST,
    output_type=_COMPANYSTATSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STONKSAPI)

DESCRIPTOR.services_by_name['StonksApi'] = _STONKSAPI

# @@protoc_insertion_point(module_scope)
