# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import stonks_pb2 as stonks__pb2


class StonksApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TelegramNotification = channel.unary_unary(
                '/StonksApi/TelegramNotification',
                request_serializer=stonks__pb2.TelegramRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetCompanyStats = channel.unary_unary(
                '/StonksApi/GetCompanyStats',
                request_serializer=stonks__pb2.CompanyStatsRequest.SerializeToString,
                response_deserializer=stonks__pb2.CompanyStatsResponse.FromString,
                )


class StonksApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TelegramNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompanyStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StonksApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TelegramNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.TelegramNotification,
                    request_deserializer=stonks__pb2.TelegramRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCompanyStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompanyStats,
                    request_deserializer=stonks__pb2.CompanyStatsRequest.FromString,
                    response_serializer=stonks__pb2.CompanyStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StonksApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StonksApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TelegramNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StonksApi/TelegramNotification',
            stonks__pb2.TelegramRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCompanyStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StonksApi/GetCompanyStats',
            stonks__pb2.CompanyStatsRequest.SerializeToString,
            stonks__pb2.CompanyStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
